language: python
notifications:
 email: false
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install -r requirements.txt
script: python -m unittest test_transformers
branches:
  only:
    - master
